site_name: rdbc documentation - {{version}}
site_author: Krzysztof Pado
site_dir: target
strict: true
pages:
    - Introduction: index.md
    - Scala API user guide:
      - Getting started: scala/gettingstarted.md
      - Core concepts: scala/core_concepts.md
      - Working with a connection: scala/connection.md
      - Statements: scala/statements.md
      - Data types: scala/types.md
      - Result Rows: scala/rows.md
      - FAQ: scala/faq.md
    - Java API user guide: java/java.md
    - Drivers: drivers.md
    - Examples: examples.md
theme: material

copyright: Copyright &copy; 2016 - 2017 rdbc contributors

extra:
  version: 1.0
  palette:
    primary: green
    accent: red
  social:
    - type: github
      link: https://github.com/rdbc-io
    - type: twitter
      link: https://twitter.com/rdbc_io

repo_name: rdbc-io/rdbc
repo_url: https://github.com/rdbc-io/rdbc
edit_uri: blob/master/rdbc-doc/docs

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.toc(permalink=true)
  - pymdownx.inlinehilite

extra_css:
  - 'css/extra.css'

google_analytics: ['UA-103140141-1', 'rdbc.io']
